Repository WHOIGit/nes-lter-ims, pull requests merged in 2023-04, with the labels that each got.

#65 Mambaforge and gdal fix
  .gitignore
  Dockerfile
  environment.yml
Labels: bug, enhancement

#66 Remove PostGIS container and associated models
  docker-compose.yml
  environment.yml
  nlweb/api/migrations/0001_initial.py
  nlweb/api/migrations/__init__.py
  nlweb/api/models.py
  nlweb/nlweb/settings.py
  requirements.txt
Labels: enhancement

#72 fixes #68
  neslter/parsing/ctd/asc.py
Labels: bug

#74 Fix duplicate columns
  neslter/parsing/ctd/asc.py
  neslter/parsing/ctd/btl.py
  neslter/parsing/ctd/common.py
  neslter/parsing/ctd/hdr.py
  neslter/workflow/ctd.py
  nlweb/api/urls.py
  nlweb/api/views.py
Labels: bug

#73 allow aphanumeric casts
  neslter/parsing/ctd/asc.py
  neslter/parsing/ctd/btl.py
  neslter/parsing/ctd/common.py
  neslter/parsing/ctd/hdr.py
  neslter/workflow/ctd.py
  nlweb/api/urls.py
  nlweb/api/views.py
Labels: enhancement

#75 Switch to generic compose configured with .env
  Dockerfile
  docker-compose.yml
  dotenv.template
  local_settings.py.template
  neslter/parsing/files.py
  nginx_templates/default.conf.template
  nlweb/api/views.py
  nlweb/nlweb/settings.py
Labels: enhancement

#77 Retain NAs in CHL output
  neslter/parsing/chl.py
Labels: enhancement

#76 fix alphanumeric casts for nut endpoint
  neslter/parsing/nut/nut.py
Labels: enhancement

#79 fix event log endpoint errors
  neslter/parsing/elog.py
Labels: bug

#84 fix cast indexing to obtain station
  neslter/parsing/elog.py
Labels: bug
